name: Publicar imagen docker

on:
    push:
        branches: 
            - main

jobs:
    build-and-push: 
        runs-on: ubuntu-latest

        steps: 
            - name: Descargar Codigo fuente del Repo
              uses: actions/checkout@v4

            - name: Inbiciar sesion en DockerHub
              uses: docker/login-action@v3
              with: 
                username: ${{secrets.DOCKERHUB_USERNAME }}
                password: ${{secrets.DOCKERHUB_TOKEN }} 
                 
            - name: Construir y Subir
              uses: docker/build-push-action@v7
              with:
                context: .
                push: true
                tags: ${{secrets.DOCKERHUB_USERNAME}}/productoms:latest